CC = g++
CC_FLAGS = -O3 -w -std=c++11 -DEIGEN_USE_BLAS
INC_FLAGS = -I /usr/include/eigen3
LIBS = -lblas

EXEC = main
SOURCES = $(wildcard *.cpp)
OBJECTS = $(SOURCES:.cpp=.o)

$(EXEC): $(OBJECTS)
	$(CC) $(CC_FLAGS) $(INC_FLAGS) $(OBJECTS) -o $(EXEC) $(LIBS)

%.o: %.cpp
	$(CC) $(CC_FLAGS) $(INC_FLAGS) -c $< -o $@ $(LIBS)

clean:
	rm -f $(EXEC) $(OBJECTS)
